### ISSUE TITLE
Ability to set a static date in HiveExt.ini

### ISSUE THREAD

**Issue by k4n30** [ayan4m1/dayz-hive#4]
as above. Is it possible to add?

**Comment by jdmanring** [comment]
Would it also be possible to set the phase of the moon and then make it static?  This would allow the date to progress for meta-gaming purposes while also giving a decent amount of ambient light at night.

**Comment by ayan4m1** [comment]
As far as I am aware the moon phase is based solely on the date, so I doubt there would be a way to do what you are proposing @jdmanring.

This is possible and something we'd like to implement in the next release or two.
