### ISSUE TITLE
Allow stored procedure execution

### ISSUE THREAD

**Issue by ayan4m1** [ayan4m1/dayz-hive#8]

**Comment by rajkosto** [comment]
Please check https://github.com/rajkosto/hive/commit/87f00ded31cff0653a63406e2b6e9cf81263b763
And test if the multiple results support works properly (currently on laptop so cannot run Arma2 server on it)
If it's confirmed working properly i will merge the multiple-results branch into my master.

**Comment by ayan4m1** [comment]
I will take care of that this weekend, thanks!
